{{- if and .Values.hermesConfig.seed.enabled (not .Values.hermesConfig.seed.existingSecret) .Values.hermesConfig.seed.config -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-webui.configSecretName" . }}
  labels:
    {{- include "hermes-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.hermesConfig.seed.secretKey }}: |-
{{ .Values.hermesConfig.seed.config | nindent 4 }}
{{- end }}
