{{- if and .Values.hermesConfig.seed.enabled (not .Values.hermesConfig.seed.existingSecret) (or .Values.hermesConfig.seed.config .Values.hermesConfig.seed.envConfig) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-webui.configSecretName" . }}
  labels:
    {{- include "hermes-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.hermesConfig.seed.config }}
  {{ $.Values.hermesConfig.seed.secretKey }}: |-
{{ . | nindent 4 }}
  {{- end }}
  {{- with .Values.hermesConfig.seed.envConfig }}
  {{ $.Values.hermesConfig.seed.envSecretKey }}: |-
{{ . | nindent 4 }}
  {{- end }}
{{- end }}
