{{- if and (not .Values.auth.existingSecret) .Values.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-webui.secretName" . }}
  labels:
    {{- include "hermes-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
